name: build

on: push

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    # 步骤
    steps:
      # 使用预制action：拉取最新的代码
      - uses: actions/checkout@v3
      # 步骤一的名称：
      - name: Install and Build
        # 该步骤运行的终端命令，进入仓库的目录，安装依赖，运行编译命令
        run:
          yarn && yarn release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
